# THIS FILE IS AUTOMATICALLY GENERATED, To edit it, see tasks.py
__all__ = [
    "__title__", "__summary__", "__uri__", "__version__",
    "__author__", "__email__", "__license__", "__copyright__",
]

__title__ = "warehouse"
__summary__ = "Next Generation Python Package Index"
__uri__ = "https://github.com/dstufft/warehouse"

__version__ = "13.09.12.0"

__author__ = "Donald Stufft"
__email__ = "donald@stufft.io"

__license__ = "Apache License, Version 2.0"
__copyright__ = "Copyright 2013 Donald Stufft"
