# SPDX-License-Identifier: Apache-2.0
"""
Add ProjectSizeLimitRequest model

Revision ID: 08aa881282ad
Revises: ff0b39808d7c
Create Date: 2026-07-19 15:06:33.974390
"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

revision = "08aa881282ad"
down_revision = "ff0b39808d7c"

# Note: It is VERY important to ensure that a migration does not lock for a
#       long period of time and to ensure that each individual migration does
#       not break compatibility with the *previous* version of the code base.
#       This is because the migrations will be ran automatically as part of the
#       deployment process, but while the previous version of the code is still
#       up and running. Thus backwards incompatible changes must be broken up
#       over multiple migrations inside of multiple pull requests in order to
#       phase them in over multiple deploys.
#
#       By default, migrations cannot wait more than 4s on acquiring a lock
#       and each individual statement cannot take more than 5s. This helps
#       prevent situations where a slow migration takes the entire site down.
#
#       If you need to increase this timeout for a migration, you can do so
#       by adding:
#
#           op.execute("SET statement_timeout = 5000")
#           op.execute("SET lock_timeout = 4000")
#
#       To whatever values are reasonable for this migration as part of your
#       migration.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "submitted", "approved", "declined", name="projectsizelimitrequeststatus"
    ).create(op.get_bind())
    op.create_table(
        "project_size_limit_requests",
        sa.Column(
            "project_id",
            sa.Uuid(),
            nullable=False,
            comment="ID of the Project the request is for",
        ),
        sa.Column(
            "submitted_by_id",
            sa.Uuid(),
            nullable=False,
            comment="ID of the User which submitted the request",
        ),
        sa.Column(
            "submitted",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Datetime the request was submitted",
        ),
        sa.Column(
            "updated",
            sa.DateTime(),
            nullable=True,
            comment="Datetime the request was last updated",
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "submitted",
                "approved",
                "declined",
                name="projectsizelimitrequeststatus",
                create_type=False,
            ),
            server_default="submitted",
            nullable=False,
            comment="Status of the request",
        ),
        sa.Column(
            "requested_limit",
            sa.BigInteger(),
            nullable=False,
            comment="Requested total project size limit, in bytes",
        ),
        sa.Column(
            "indexes",
            sa.String(),
            nullable=False,
            comment="Which package indexes the increase is requested for",
        ),
        sa.Column(
            "about_project",
            sa.String(),
            nullable=False,
            comment="What the project is and how long it has been active",
        ),
        sa.Column(
            "release_size",
            sa.String(),
            nullable=False,
            comment="Description of the size of each release",
        ),
        sa.Column(
            "release_frequency",
            sa.String(),
            nullable=False,
            comment="How frequently releases are made",
        ),
        sa.Column(
            "admin_message",
            sa.String(),
            nullable=True,
            comment="Optional note left by the admin who reviewed the request",
        ),
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submitted_by_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_size_limit_requests_project_id"),
        "project_size_limit_requests",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_project_size_limit_requests_submitted"),
        "project_size_limit_requests",
        ["submitted"],
        unique=False,
    )
    op.create_index(
        "project_size_limit_requests_pending_project_uniq",
        "project_size_limit_requests",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("status = 'submitted'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "project_size_limit_requests_pending_project_uniq",
        table_name="project_size_limit_requests",
    )
    op.drop_index(
        op.f("ix_project_size_limit_requests_submitted"),
        table_name="project_size_limit_requests",
    )
    op.drop_index(
        op.f("ix_project_size_limit_requests_project_id"),
        table_name="project_size_limit_requests",
    )
    op.drop_table("project_size_limit_requests")
    sa.Enum(
        "submitted", "approved", "declined", name="projectsizelimitrequeststatus"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
