# SPDX-License-Identifier: Apache-2.0
"""
New Sponsor columns to save data from pythondotorg API

Revision ID: 19cf76d2d459
Revises: 29a8901a4635
Create Date: 2022-02-13 14:31:18.366248
"""

import sqlalchemy as sa

from alembic import op

revision = "19cf76d2d459"
down_revision = "29a8901a4635"

# Note: It is VERY important to ensure that a migration does not lock for a
#       long period of time and to ensure that each individual migration does
#       not break compatibility with the *previous* version of the code base.
#       This is because the migrations will be ran automatically as part of the
#       deployment process, but while the previous version of the code is still
#       up and running. Thus backwards incompatible changes must be broken up
#       over multiple migrations inside of multiple pull requests in order to
#       phase them in over multiple deploys.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsors", sa.Column("origin", sa.String(), nullable=True))
    op.add_column("sponsors", sa.Column("level_name", sa.String(), nullable=True))
    op.add_column("sponsors", sa.Column("level_order", sa.Integer(), nullable=True))
    op.add_column("sponsors", sa.Column("slug", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sponsors", "slug")
    op.drop_column("sponsors", "level_order")
    op.drop_column("sponsors", "level_name")
    op.drop_column("sponsors", "origin")
    # ### end Alembic commands ###
