# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Draft Releases

Revision ID: 2886ca342478
Revises: 87509f4ae027
Create Date: 2020-07-17 21:33:46.993326
"""

from alembic import op
import sqlalchemy as sa


revision = "2886ca342478"
down_revision = "87509f4ae027"

# Note: It is VERY important to ensure that a migration does not lock for a
#       long period of time and to ensure that each individual migration does
#       not break compatibility with the *previous* version of the code base.
#       This is because the migrations will be ran automatically as part of the
#       deployment process, but while the previous version of the code is still
#       up and running. Thus backwards incompatible changes must be broken up
#       over multiple migrations inside of multiple pull requests in order to
#       phase them in over multiple deploys.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("releases", sa.Column("project_name", sa.Text(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION make_draft_hash(project_name text, version text) returns text as $$
                SELECT  md5(project_name || version)
            $$
            LANGUAGE SQL
            IMMUTABLE
            RETURNS NULL ON NULL INPUT;
    """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("releases", "project_name")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION make_draft_hash")
