# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
empty message

Revision ID: 4656a576b6
Revises: 28a7e805fd0
Create Date: 2015-04-13 20:14:35.223465
"""

from alembic import op
import sqlalchemy as sa


revision = '4656a576b6'
down_revision = '28a7e805fd0'

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('updated', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'updated')
    ### end Alembic commands ###
