# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
project description cache fields

Revision ID: 628ea7069e3e
Revises: 6714f3f04f0f
Create Date: 2018-04-18 05:55:01.222046
"""

from alembic import op
import sqlalchemy as sa


revision = '628ea7069e3e'
down_revision = '6714f3f04f0f'

# Note: It is VERY important to ensure that a migration does not lock for a
#       long period of time and to ensure that each individual migration does
#       not break compatibility with the *previous* version of the code base.
#       This is because the migrations will be ran automatically as part of the
#       deployment process, but while the previous version of the code is still
#       up and running. Thus backwards incompatible changes must be broken up
#       over multiple migrations inside of multiple pull requests in order to
#       phase them in over multiple deploys.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'releases',
        sa.Column('rendered_description', sa.Text(), nullable=True))
    op.add_column(
        'releases',
        sa.Column('renderer_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'renderer_version')
    op.drop_column('releases', 'rendered_description')
    # ### end Alembic commands ###
