# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
create_team_models

Revision ID: 7eaad728b806
Revises: 5a095c98f812
Create Date: 2022-06-13 13:23:42.629088
"""

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

revision = "7eaad728b806"
down_revision = "5a095c98f812"

# Note: It is VERY important to ensure that a migration does not lock for a
#       long period of time and to ensure that each individual migration does
#       not break compatibility with the *previous* version of the code base.
#       This is because the migrations will be ran automatically as part of the
#       deployment process, but while the previous version of the code is still
#       up and running. Thus backwards incompatible changes must be broken up
#       over multiple migrations inside of multiple pull requests in order to
#       phase them in over multiple deploys.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        r""" CREATE OR REPLACE FUNCTION normalize_team_name(text)
            RETURNS text AS
            $$
                SELECT lower(regexp_replace($1, '(\s|/|\.|_|-)+', '-', 'ig'))
            $$
            LANGUAGE SQL
            IMMUTABLE
            RETURNS NULL ON NULL INPUT;
        """
    )
    op.create_table(
        "teams",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            r"name ~* '^([^\s/._-]|[^\s/._-].*[^\s/._-])$'::text",
            name="teams_valid_name",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_created"), "teams", ["created"], unique=False)
    op.create_index(
        "teams_organization_id_idx", "teams", ["organization_id"], unique=False
    )
    op.create_table(
        "team_project_roles",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("role_name", sa.Text(), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "team_id", name="_team_project_roles_project_team_uc"
        ),
    )
    op.create_index(
        "team_project_roles_project_id_idx",
        "team_project_roles",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "team_project_roles_team_id_idx",
        "team_project_roles",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "team_roles",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("role_name", sa.Text(), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "team_id", name="_team_roles_user_team_uc"),
    )
    op.create_index("team_roles_team_id_idx", "team_roles", ["team_id"], unique=False)
    op.create_index("team_roles_user_id_idx", "team_roles", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("team_roles_user_id_idx", table_name="team_roles")
    op.drop_index("team_roles_team_id_idx", table_name="team_roles")
    op.drop_table("team_roles")
    op.drop_index("team_project_roles_team_id_idx", table_name="team_project_roles")
    op.drop_index("team_project_roles_project_id_idx", table_name="team_project_roles")
    op.drop_table("team_project_roles")
    op.drop_index("teams_organization_id_idx", table_name="teams")
    op.drop_index(op.f("ix_teams_created"), table_name="teams")
    op.drop_table("teams")
    op.execute("DROP FUNCTION normalize_team_name(text)")
    # ### end Alembic commands ###
