# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
text

Revision ID: 9b6babb05318
Revises: bc8f7b526961
Create Date: 2020-06-25 22:37:25.343522
"""

from alembic import op
import sqlalchemy as sa


revision = '9b6babb05318'
down_revision = 'bc8f7b526961'

# Note: It is VERY important to ensure that a migration does not lock for a
#       long period of time and to ensure that each individual migration does
#       not break compatibility with the *previous* version of the code base.
#       This is because the migrations will be ran automatically as part of the
#       deployment process, but while the previous version of the code is still
#       up and running. Thus backwards incompatible changes must be broken up
#       over multiple migrations inside of multiple pull requests in order to
#       phase them in over multiple deploys.

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('release_files', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('releases', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releases', 'deleted')
    op.drop_column('release_files', 'deleted')
    op.drop_column('projects', 'deleted')
    # ### end Alembic commands ###
