# SPDX-License-Identifier: Apache-2.0
"""
Add upload and total size limits to organizations

Revision ID: a6994b8bed95
Revises: 30c837b1425a
Create Date: 2025-08-06 22:47:15.411024
"""

import sqlalchemy as sa

from alembic import op

revision = "a6994b8bed95"
down_revision = "30c837b1425a"

# Note: It is VERY important to ensure that a migration does not lock for a
#       long period of time and to ensure that each individual migration does
#       not break compatibility with the *previous* version of the code base.
#       This is because the migrations will be ran automatically as part of the
#       deployment process, but while the previous version of the code is still
#       up and running. Thus backwards incompatible changes must be broken up
#       over multiple migrations inside of multiple pull requests in order to
#       phase them in over multiple deploys.
#
#       By default, migrations cannot wait more than 4s on acquiring a lock
#       and each individual statement cannot take more than 5s. This helps
#       prevent situations where a slow migration takes the entire site down.
#
#       If you need to increase this timeout for a migration, you can do so
#       by adding:
#
#           op.execute("SET statement_timeout = 5000")
#           op.execute("SET lock_timeout = 4000")
#
#       To whatever values are reasonable for this migration as part of your
#       migration.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "upload_limit",
            sa.Integer(),
            nullable=True,
            comment=(
                "Maximum file size limit in bytes for projects in this organization"
            ),
        ),
    )
    op.add_column(
        "organizations",
        sa.Column(
            "total_size_limit",
            sa.BigInteger(),
            nullable=True,
            comment=(
                "Maximum total size limit in bytes for projects in this organization"
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "total_size_limit")
    op.drop_column("organizations", "upload_limit")
    # ### end Alembic commands ###
