# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
python:
  install:
    - requirements: requirements/docs/dev.txt
    - requirements: requirements/docs/user.txt

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  commands:
    - |
        if [ "$READTHEDOCS_PROJECT" = "warehouse" ]
        then
          make -C docs/ html;
          mv docs/_build/html _readthedocs/html;
        fi
    - |
        if [ "$READTHEDOCS_PROJECT" = "docspypiorg" ]
        then
          mkdocs build -f user-docs/mkdocs.yml;
          mv user-docs/site _readthedocs/html;
        fi
