#!/bin/sh

# Create a Database
createdb warehouse

# Install the CIText extension
psql warehouse -c 'CREATE EXTENSION IF NOT EXISTS citext'

# Install the UUID extension
psql warehouse -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'

# Migrate the database to the latest schema
warehouse -c dev/config.yml migrate upgrade head

# Initialise the ElasticSearch index
warehouse -c dev/config.yml search reindex

echo
echo '-------------------------------------------------'
echo "Dev environment set up."
echo "Run ./dev-start-server to start up a dev server."
echo '-------------------------------------------------'
