blank_issues_enabled: false
contact_links:
  - name: Python Infrastructure Status Page
    url: https://status.python.org/
    about: Check here first for ongoing outages or incidents affecting PyPI.
  - name: PyPI Support
    url: https://github.com/pypi/support/issues/new/choose
    about: >-
      Account recovery, 2FA, network or connection problems, limit increases,
      organizations, and name retention requests.
  - name: PyPI User Documentation
    url: https://docs.pypi.org/
    about: Official PyPI documentation. Please check here before opening an issue.
  - name: PyPI Developer Documentation
    url: https://warehouse.pypa.io/
    about: Documentation for developers working on PyPI.
  - name: "(Maintainers Only) Blank issue"
    url: https://github.com/pypi/warehouse/issues/new
    about: For maintainers only.
