FROM opensearchproject/opensearch:2.12.0

RUN opensearch-plugin remove opensearch-skills --purge
RUN opensearch-plugin remove opensearch-ml --purge
RUN opensearch-plugin remove opensearch-neural-search --purge
RUN opensearch-plugin remove opensearch-performance-analyzer --purge
RUN opensearch-plugin remove opensearch-security-analytics --purge
