openapi: 3.0.0
info:
  title: Warehouse Management API
  description: "**BETA** API for managing warehouse interactions"
  version: 0.0.0
servers:
  - url: http://localhost
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      description: "[PyPI API Token](https://pypi.org/help/#apitoken)"
      type: http
      scheme: bearer
      bearerFormat: API Token
  parameters:
    pypi_api_version:
      name: PyPI-API-Version
      # FIXME: Use a real URL once it exists
      description: "Required header for API versioning. See [API Versioning](https://warehouse.pypa.io/api-reference/versioning/) for more information."
      in: header
      required: true
      schema:
        type: string
        enum: [ "api-v0-danger", "api-v1" ]
        example: "api-v0-danger"
security:
  - bearerAuth: [ ]

paths:
  /danger-api/echo:
    parameters:
      - $ref: '#/components/parameters/pypi_api_version'
    get:
      summary: Echo Username
      description: Echo username of authenticated user. Likely to be omitted from v1.
      operationId: echoUsername
      responses:
        '200':
          description: Echo username of authenticated user
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: someuser
                example: { "username": "someuser" }
        '400':
            description: Bad request
