openapi: 3.0.0
info:
  title: Warehouse Management API
  description: "**BETA** API for managing warehouse interactions"
  version: 0.0.0
servers:
  - url: http://localhost
    description: Local development server

components:
  securitySchemes:
    bearerAuth:
      description: "[PyPI API Token](https://pypi.org/help/#apitoken)"
      type: http
      scheme: bearer
      bearerFormat: API Token
security:
  - bearerAuth: [ ]

tags:
  - name: danger-api
    description: "[Danger Zone API](https://blog.pypi.org/posts/2024-03-06-malware-reporting-evolved/#via-api)"

paths:
  /danger-api/echo:
    get:
      summary: Echo Username
      description: Echo username of authenticated user. Likely to be omitted from v1.
      operationId: echoUsername
      tags:
        - danger-api
      responses:
        '200':
          description: Echo username of authenticated user
          content:
            application/vnd.pypi.api-v0-danger+json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    example: someuser
                example: { "username": "someuser" }
        '400':
            description: Bad request
