name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:  # generally only for the "combine-prs" workflow
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  build:
    if: github.repository == 'pypi/warehouse'
    runs-on: depot-ubuntu-24.04-arm
    outputs:
      buildId: ${{ steps.build.outputs.build-id}}
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Set up Depot CLI
        uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1.6.0
      - name: Build image
        id: build
        uses: depot/build-push-action@9785b135c3c76c33db102e45be96a25ab55cd507 # v1.16.2
        with:
          save: true
          build-args: |
            DEVEL=yes
            CI=yes
          tags: pypi/warehouse:ci-${{ github.run_id }}

  ci:
    if: github.repository == 'pypi/warehouse'
    needs: build
    uses: ./.github/workflows/ci-base.yml
    with:
      runner: depot-ubuntu-24.04-arm
      runner_large: depot-ubuntu-24.04-arm-4
      image_registry: registry.depot.dev/rltf7cln5v
      build_id: ${{ needs.build.outputs.buildId }}
      use_depot: true
    permissions:
      id-token: write
      packages: read