# Origin: https://github.com/marketplace/actions/combine-prs

name: "Combine PRs"

# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      ignoreLabel:
        description: "Exclude PRs with this label"
        required: true
        default: "blocked"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "combine-prs"
  combine-prs:
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      contents: write
      pull-requests: write
      checks: read
      actions: write
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    steps:
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: generate_token
        with:
          app-id: ${{ secrets.COMBINE_PRS_APP_ID }}
          private-key: ${{ secrets.COMBINE_PRS_PRIVATE_KEY }}
          # https://github.com/github/combine-prs#permissions
          permission-contents: write
          permission-pull-requests: write
          permission-checks: read

      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@2909f404763c3177a456e052bdb7f2e85d3a7cb3 # v5.2.0
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          ignore_label: ${{ github.event.inputs.ignoreLabel || 'blocked' }}
