# https://github.com/woodruffw/zizmor
name: GitHub Actions Security Analysis with Zizmor

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  zizmor:
    # Advanced Security is not enabled on private repositories
    if: github.repository == 'pypi/warehouse'
    name: Zizmor
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      # required for workflows in private repositories
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      - name: Run zizmor
        run: pipx run zizmor --format sarif . > results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: zizmor
